version: "3"

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    command: sh -c "npm run nodemon"
    # ports:
      # - '5433'
  db:
    image: postgres:latest
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=some
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  # db:
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - ./.data/db/.data:/var/lib/mysql
  #   #   - ./.data/db/conf.d:/etc/mysql/conf.d
  #   #   - ./.data/log:/var/log/container
  #   ports:
  #     - '3030:3000'
